- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart buildslave
  service: name=buildslave state=restarted

- name: restart buildbot-worker
  systemd: name=buildbot-worker@osmose state=restarted
