- name: install packages
  apt:
    pkg:
      - buildbot-worker

- name: init paths
  file: path={{ item }} state=directory owner=buildbot group=buildbot force=no
  with_items:
    - /data/work/buildbot-slave

- name: add sudoers to access osmose user
  copy: src=sudoers dest=/etc/sudoers.d/buildbot-slave mode=0440 owner=root group=root validate='visudo -cf %s'

- name: configure buildbot directory
  become: yes
  become_user: buildbot
  command:
    creates="/data/work/buildbot-slave/buildbot.tac" chdir="/data/work/buildbot-slave/"
    /usr/bin/buildbot-worker create-worker . buildbot.osmose.openstreetmap.fr:9989 {{ inventory_hostname.split(".") | first }} "{{ lookup('password', 'credentials/' + inventory_hostname + '/buildbot-slave-password length=15 chars=ascii_letters,digits') }}"

- name: copy systemd service
  copy:
    src: /lib/systemd/system/buildbot-worker@.service
    dest: /etc/systemd/system/buildbot-worker@osmose.service
    remote_src: yes
    force: no
  notify: restart buildbot-worker

- name: modify systemd service
  lineinfile:
    dest: /etc/systemd/system/buildbot-worker@osmose.service
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "ConditionDirectoryNotEmpty=",   line: "ConditionDirectoryNotEmpty=/data/work/buildbot-slave"}
    - {regexp: "ConditionFileNotEmpty=",   line: "ConditionFileNotEmpty=/data/work/buildbot-slave/buildbot.tac"}
    - {regexp: "WorkingDirectory=",   line: "WorkingDirectory=/data/work/buildbot-slave"}
  notify: restart buildbot-worker

- name: create systemd override for buildbot-worker
  file:
    path: /etc/systemd/system/buildbot-worker@osmose.service.d/
    state: directory

- name: add systemd override for postgresql
  template:
    dest: "/etc/systemd/system/buildbot-worker@osmose.service.d/override.conf"
    src: "systemd-buildbot-worker-override.conf"
    owner: root
  notify:
    - systemd daemon-reload
    - restart buildbot-worker

- name: enable systemd service
  systemd:
    name: "{{ item }}"
    masked: no
    enabled: yes
    daemon_reload: yes
  with_items:
    - buildbot-worker@osmose.service
  notify: restart buildbot-worker
