---
- name: Create root project_dir and work_dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /data/project
    - /data/work

- name: Set project_dir and work_dir
  ansible.builtin.set_fact:
    project_dir: /data/project/{{ user }}
    work_dir: /data/work/{{ user }}

- name: Init user ${user}
  ansible.builtin.user:
    name: "{{ user }}"
    home: "{{ project_dir }}"
    shell: /bin/bash
    generate_ssh_key: "{{ generate_ssh_key | default('no') }}"
    system: "{{ user_system | default('no') }}"

- name: Init group ${user}
  ansible.builtin.group:
    name: "{{ user }}"

- name: Check if /data exists
  ansible.builtin.stat:
    path: /data
  register: data_exists

- name: Init /data path
  ansible.builtin.file:
    path: /data
    state: directory
    mode: "0755"
  when: not data_exists.stat.exists

- name: Init /data/work/ path for ${user}
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Copy default config files
  ansible.builtin.copy:
    force: false
    src: shared/files/default{{ item }}
    dest: "{{ project_dir }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_items:
    - .gitconfig
    - .vimrc
